# ==========================================
# Knoc (\uB178\uD06C) Spring Boot Base Configuration
# ==========================================
spring.application.name=knoc

# \uB3C4\uCEE4 \uBE44\uD65C\uC131\uD654
spring.docker.compose.enabled=false

# 1. \uAE30\uBCF8 \uD65C\uC131 \uD504\uB85C\uD30C\uC77C \uC124\uC815 (\uB85C\uCEEC \uAC1C\uBC1C \uC2DC\uC5D0\uB294 \uAE30\uBCF8\uAC12\uC744 \uC0AC\uC6A9\uD558\uB3C4\uB85D \uC124\uC815 \uAC00\uB2A5)
spring.profiles.active=prod

# 2. \uACF5\uD1B5 Thymeleaf \uC124\uC815
spring.thymeleaf.cache=false

# 3. \uACF5\uD1B5 Swagger (OpenAPI) \uC124\uC815
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.groups-order=DESC
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true

# 4. \uB85C\uAE45 \uACF5\uD1B5 \uC124\uC815
logging.level.org.hibernate.orm.jdbc.bind=TRACE