# ==========================================
# Knoc (??) Spring Boot Base Configuration
# ==========================================
spring.application.name=knoc

# ?? ????
spring.docker.compose.enabled=false

# 1. ?? ?? ???? ?? (?? ?? ??? ???? ????? ?? ??)
spring.profiles.active=prod

# 2. ?? Thymeleaf ??
spring.thymeleaf.cache=false

# 3. ?? Swagger (OpenAPI) ??
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.groups-order=DESC
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true

# 4. ?? ?? ??
logging.level.org.hibernate.orm.jdbc.bind=TRACE